# Generated by Django 3.2.19 on 2024-01-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_database', '0004_rename_traings_faculty_coursedata_trainings_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedata',
            old_name='sustainibility_factors',
            new_name='additional_details',
        ),
        migrations.RenameField(
            model_name='coursedata',
            old_name='frequency_of_training',
            new_name='frequency_of_running_of_course',
        ),
        migrations.RenameField(
            model_name='coursedata',
            old_name='funding_schemes',
            new_name='funding_availability',
        ),
        migrations.RenameField(
            model_name='coursedata',
            old_name='teaching_approach',
            new_name='methods_of_teaching',
        ),
        migrations.RenameField(
            model_name='coursedata',
            old_name='target_population',
            new_name='population_focus',
        ),
        migrations.RemoveField(
            model_name='coursedata',
            name='key_challenges',
        ),
        migrations.RemoveField(
            model_name='coursedata',
            name='numbers_since_2015',
        ),
        migrations.RemoveField(
            model_name='coursedata',
            name='trainings_faculty',
        ),
    ]
